name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-run-unit-test:
    name: Build, run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository in ubuntu's file system
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

  build-and-run-instrumented-tests:
    name: Run Instrumented tests
    runs-on: macos-latest
    steps:
      - name: Checkout current repository in macos' file system
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck --stacktrace

  upload-test-reports:
    name: Upload test reports
    runs-on: ubuntu-latest
    needs:
      - build-and-run-unit-test
      - build-and-run-instrumented-tests
    steps:
      - name: Checkout current repository in ubuntu's file system
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports

  generate-apk:
    name: Generate and upload debug apk
    runs-on: ubuntu-latest
    needs:
      - build-and-run-unit-test
      - build-and-run-instrumented-tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Generate debug apk
        run: ./gradlew assembleDebug

      - name: Upload apk
        uses: actions/upload-artifact@v1
        with:
          name: build-output
          path: app/build/outputs/apk/debug/app-debug.apk



